# Generated by Django 5.2.7 on 2025-11-20 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockphoto',
            name='title',
        ),
        migrations.AlterField(
            model_name='clockphoto',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='ClockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clock.clockphoto')),
            ],
        ),
    ]
