# Generated by Django 5.2.7 on 2025-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work09', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
